branches:
  only:
    - master

language: node_js

node_js:
  - "0.11"

before_script:
  - "npm install -g grunt-cli"
  - "npm install"

script:
  - "NODE_ENV=test node --harmony `which grunt`"

notifications:
  email:
    - ram@hiddentao.com

